# Generated by Django 5.2.1 on 2025-05-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_shelter_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptioninquiry',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Denied', 'Denied')], default='Pending', max_length=20),
        ),
    ]
