# Generated by Django 5.2.1 on 2025-05-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_adoptioninquiry_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptioninquiry',
            name='message',
        ),
        migrations.AddField(
            model_name='adoptioninquiry',
            name='address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adoptioninquiry',
            name='currently_own_pet',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adoptioninquiry',
            name='full_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adoptioninquiry',
            name='phone_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adoptioninquiry',
            name='prior_experience',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
